"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type CategoryRow = { id:string; title:string; source_organization:string; source_indicator_code:string; enabled:boolean; eligible_daily:boolean; quality_score:number; country_coverage:number; latest_available_year:number|null; family:string };
type ImportRow = { id:number; source_organization:string; status:string; started_at:string; completed_at:string|null; categories_processed:number; observations_inserted:number; error_message:string|null; details?: Record<string, unknown> };
type Dashboard = { stats:{categories:number;observations:number;countries:number}; sources:any[]; imports:ImportRow[]; categories:CategoryRow[]; boards:Record<string,boolean>; todayScoreCount:number };
type DailyMode = "easy" | "normal" | "expert";
type GeneratedBoard = { countries:string[]; categories:string[] };
type ScoreBreakdown = { overall:number; quality:number; variety:number; geography:number; difficultyFit:number; competitiveness:number };
type GenerationDiagnostics = {
 eligibleDatasets:number;
 requiredDatasets:number;
 attempts:number;
 validCandidates:Partial<Record<DailyMode,number>>;
 failureStage?:string;
 message?:string;
};
type GenerationResult = { date:string; diagnostics:GenerationDiagnostics; scores:Record<DailyMode,ScoreBreakdown>; boards:Record<DailyMode,GeneratedBoard> };

export default function AdminDashboard(){
 const [data,setData]=useState<Dashboard|null>(null); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [source,setSource]=useState("all"); const [running,setRunning]=useState(false); const [generating,setGenerating]=useState(false); const [generation,setGeneration]=useState<GenerationResult|null>(null); const [progress,setProgress]=useState({done:0,total:0,label:""});
 const load=useCallback(async()=>{ const r=await fetch('/api/admin/dashboard',{cache:'no-store'}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Dashboard could not load.'); setData(j); },[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 const boardsLocked=(data?.todayScoreCount??0)>0;
 const validCandidateCount=generation?Object.values(generation.diagnostics.validCandidates).reduce<number>((sum,count)=>sum+(count??0),0):0;
 const filtered=useMemo(()=>data?.categories.filter(c=>(source==='all'||c.source_organization===source)&&(`${c.title} ${c.source_indicator_code} ${c.family}`.toLowerCase().includes(query.toLowerCase())))??[],[data,query,source]);
 async function post(body:any){const r=await fetch('/api/admin/import/world-bank',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Import failed.');return j;}

 async function generateBoards(){if(generating)return;setGenerating(true);setError("");try{const r=await fetch('/api/admin/daily/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j.error||'Daily generation failed.'),{diagnostics:j.diagnostics});setGeneration(j);await load();}catch(e:any){const d=e.diagnostics;setError(d?`${e.message} Eligible datasets: ${d.eligibleDatasets??'—'}; attempts: ${d.attempts??'—'}; stage: ${d.failureStage??'unknown'}.`:e.message);}finally{setGenerating(false);}}
 async function importWorldBank(){ if(running)return; setRunning(true);setError('');try{const start=await post({action:'start'});setProgress({done:0,total:start.categories.length,label:'Preparing World Bank categories'});let failures:any[]=[];for(let i=0;i<start.categories.length;i++){const c=start.categories[i];setProgress({done:i,total:start.categories.length,label:c.shortName});try{await post({action:'category',runId:start.runId,categoryId:c.id});}catch(e:any){failures.push({id:c.id,error:e.message});}}await post({action:'finish',runId:start.runId,failures});setProgress({done:start.categories.length,total:start.categories.length,label:failures.length?`Completed with ${failures.length} warning${failures.length===1?'':'s'}`:'Import completed'});await load();}catch(e:any){setError(e.message);}finally{setRunning(false);}}
 if(!data)return <section className="adminLoading">{error||'Loading warehouse…'}</section>;
 return <>
  {error&&<div className="adminError">{error}</div>}
  <section className="adminStatGrid"><article><span>Categories</span><strong>{data.stats.categories.toLocaleString()}</strong></article><article><span>Countries</span><strong>{data.stats.countries.toLocaleString()}</strong></article><article><span>Observations</span><strong>{data.stats.observations.toLocaleString()}</strong></article><article><span>Today’s boards</span><strong>{Object.values(data.boards).filter(Boolean).length}/3</strong><small>Easy · Normal · Expert</small></article></section>
  <section className="adminPanel puzzleIntelligence"><div className="adminPanelHead"><div><span className="kicker">Puzzle intelligence</span><h2>Today’s optimized boards</h2><p>Searches hundreds of valid candidates per mode, scores them, and saves the strongest distinct trio.</p></div><button className="adminPrimary" disabled={generating||running||boardsLocked} onClick={generateBoards}>{generating?'Optimizing boards…':boardsLocked?'Boards locked after play':Object.values(data.boards).some(Boolean)?'Regenerate today’s boards':'Generate today’s boards'}</button></div>{boardsLocked&&<p className="adminEmpty">Today’s boards already have saved scores, so regeneration is disabled to protect the leaderboard and one-attempt rule.</p>}{generation?<><div className="diagnosticStrip"><strong>{generation.diagnostics.eligibleDatasets} eligible datasets</strong><span>{generation.diagnostics.attempts} trio attempts</span><span>{validCandidateCount} valid candidates evaluated</span></div><div className="boardPreviewGrid">{(['easy','normal','expert'] as const).map(mode=><article className="boardPreview" key={mode}><div className="boardPreviewHead"><div><span>{mode}</span><strong>{generation.scores[mode].overall}</strong></div><small>Optimization score</small></div><div className="scoreBars"><span>Quality {generation.scores[mode].quality}</span><span>Variety {generation.scores[mode].variety}</span><span>Geography {generation.scores[mode].geography}</span><span>Difficulty {generation.scores[mode].difficultyFit}</span></div><h3>Countries</h3><p>{generation.boards[mode].countries.join(' · ')}</p><h3>Categories</h3><p>{generation.boards[mode].categories.join(' · ')}</p></article>)}</div></>:<p className="adminEmpty">Generate the trio to see candidate diagnostics and previews here. Existing saved boards remain playable until replaced.</p>}</section>
  <section className="adminPanel"><div className="adminPanelHead"><div><span className="kicker">Data sources</span><h2>Warehouse imports</h2></div></div><div className="sourceGrid">
   {data.sources.map((s:any)=><article className="sourceCard" key={s.id}><div><h3>{s.name}</h3><span className={s.id==='worldbank'?'statusPill active':'statusPill'}>{s.id==='worldbank'?'Ready':'Coming soon'}</span></div><p>{s.description}</p>{s.id==='worldbank'?<button disabled={running} onClick={importWorldBank}>{running?'Importing…':'Refresh World Bank'}</button>:<button disabled>Not available yet</button>}</article>)}
  </div>{progress.total>0&&<div className="importProgress"><div><strong>{progress.label}</strong><span>{progress.done}/{progress.total}</span></div><progress max={progress.total} value={progress.done}/></div>}</section>
  <section className="adminPanel"><span className="kicker">Import history</span><h2>Recent runs</h2>{data.imports.length?<div className="adminTableWrap"><table><thead><tr><th>Source</th><th>Status</th><th>Started</th><th>Categories</th><th>Observations</th></tr></thead><tbody>{data.imports.map(r=><tr key={r.id}><td>{r.source_organization}</td><td><span className={`runStatus ${r.status}`}>{r.status}</span></td><td>{new Date(r.started_at).toLocaleString()}</td><td>{r.categories_processed}</td><td>{r.observations_inserted.toLocaleString()}</td></tr>)}</tbody></table></div>:<p className="adminEmpty">No imports yet.</p>}</section>
  <section className="adminPanel"><div className="adminPanelHead"><div><span className="kicker">Category library</span><h2>{filtered.length} categories</h2></div><div className="categoryFilters"><input aria-label="Search categories" placeholder="Search categories…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{[...new Set(data.categories.map(c=>c.source_organization))].map(s=><option key={s}>{s}</option>)}</select></div></div><div className="adminTableWrap"><table><thead><tr><th>Enabled</th><th>Category</th><th>Source</th><th>Indicator</th><th>Quality</th><th>Daily</th><th>Coverage</th><th>Latest year</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td>{c.enabled?'✓':'—'}</td><td><strong>{c.title}</strong><small>{c.family}</small></td><td>{c.source_organization}</td><td><code>{c.source_indicator_code}</code></td><td><strong>{c.quality_score || '—'}</strong></td><td>{c.eligible_daily?'✓':'—'}</td><td>{c.country_coverage}</td><td>{c.latest_available_year??'—'}</td></tr>)}</tbody></table></div></section>
 </>;
}
