import { createHash } from "crypto";
import { NextResponse } from "next/server";
import { requireAdmin } from "../../../../../lib/supabase/adminAuth";
import { fetchCountries } from "../../../../../lib/worldBank";
import { generateDailyTrio } from "../../../../../lib/puzzleEngine";
import { encodeRound } from "../../../../../lib/challengeCodec";
import { DAILY_DIFFICULTIES } from "../../../../../lib/gameRules";
import { DATASET_VERSION, RULES_VERSION, CATEGORY_SET_VERSION } from "../../../../../lib/version";
import { newYorkDate } from "../../../../../lib/time";
export const dynamic="force-dynamic";export const maxDuration=300;
function validDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value);}
export async function POST(request:Request){const auth=await requireAdmin();if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const body=await request.json().catch(()=>({}));const date=typeof body.date==="string"?body.date:newYorkDate();if(!validDate(date))return NextResponse.json({error:"Invalid date."},{status:400});try{const [{count:scoreCount,error:scoreError},{count:boardCount,error:boardError}]=await Promise.all([auth.admin.from("daily_scores").select("id",{count:"exact",head:true}).eq("challenge_date",date),auth.admin.from("daily_challenges").select("difficulty",{count:"exact",head:true}).eq("challenge_date",date)]);if(scoreError)throw scoreError;if(boardError)throw boardError;if((scoreCount??0)>0&&(boardCount??0)>0)return NextResponse.json({error:"Today’s boards already have saved player scores and are locked against regeneration."},{status:409});const countries=await fetchCountries();const generated=await generateDailyTrio(countries,date);const rows=DAILY_DIFFICULTIES.map(d=>{const encoded=encodeRound(generated.trio[d]);return{challenge_date:date,difficulty:d,seed:`DAILY-${d.toUpperCase()}-${date}`,encoded_board:encoded,board_hash:createHash("sha256").update(encoded).digest("hex"),dataset_version:DATASET_VERSION,rules_version:RULES_VERSION,category_set_version:CATEGORY_SET_VERSION};});const {error}=await auth.admin.from("daily_challenges").upsert(rows,{onConflict:"challenge_date,difficulty"});if(error)throw error;return NextResponse.json({ok:true,date,diagnostics:generated.diagnostics,scores:generated.scores,boards:Object.fromEntries(DAILY_DIFFICULTIES.map(d=>[d,{countries:generated.trio[d].bank.map(c=>c.name),categories:generated.trio[d].categories.map(c=>c.category.name)}]))});}catch(error:any){return NextResponse.json({error:error?.message||"Daily generation failed.",diagnostics:error?.diagnostics??null},{status:500});}}
