create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[A-Za-z0-9_]{3,20}$'),
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_challenges (
  challenge_date date not null,
  difficulty text not null default 'easy' check (difficulty in ('easy','expert')),
  seed text not null,
  encoded_board text not null,
  board_hash text not null,
  dataset_version text not null,
  rules_version text not null,
  category_set_version text not null,
  created_at timestamptz not null default now(),
  primary key (challenge_date, difficulty)
);

create table if not exists public.daily_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  challenge_date date not null,
  difficulty text not null default 'easy' check (difficulty in ('easy','expert')),
  score integer not null check (score between 0 and 800),
  average_placement numeric(5,2) not null check (average_placement between 1 and 10),
  firsts integer not null default 0 check (firsts between 0 and 8),
  top_fives integer not null default 0 check (top_fives between 0 and 8),
  assignments jsonb not null,
  completed_at timestamptz not null default now(),
  unique (user_id, challenge_date, difficulty),
  foreign key (challenge_date, difficulty) references public.daily_challenges(challenge_date, difficulty) on delete cascade
);

create index if not exists daily_scores_user_idx on public.daily_scores(user_id);
create index if not exists daily_scores_date_score_idx on public.daily_scores(challenge_date, difficulty, score desc);

alter table public.profiles enable row level security;
alter table public.daily_challenges enable row level security;
alter table public.daily_scores enable row level security;

create policy "profiles are publicly readable" on public.profiles for select using (true);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "daily challenges are publicly readable" on public.daily_challenges for select using (true);
create policy "scores are publicly readable" on public.daily_scores for select using (true);
create policy "users insert own scores" on public.daily_scores for insert with check (auth.uid() = user_id);
create policy "users update own scores" on public.daily_scores for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  base_name text;
  candidate text;
begin
  base_name := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'user_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1), 'player'), '[^a-zA-Z0-9_]', '', 'g'));
  if length(base_name) < 3 then base_name := 'player'; end if;
  candidate := left(base_name, 15) || '_' || substr(replace(new.id::text, '-', ''), 1, 4);
  insert into public.profiles (id, username, display_name)
  values (new.id, candidate, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
