-- GeoStats data warehouse schema
-- Step 1: create category metadata, country observations, latest-value view,
-- and import-run logging. Safe to run once in Supabase SQL Editor.

begin;

create table if not exists public.stat_categories (
  id text primary key,
  title text not null,
  short_title text,
  description text not null,
  icon text,
  unit text not null,
  value_type text not null check (value_type in ('total', 'per_capita', 'percentage', 'rate', 'index', 'other')),
  ranking_direction text not null check (ranking_direction in ('high', 'low')),
  family text not null,
  source_organization text not null,
  source_dataset text not null,
  source_indicator_code text not null,
  source_url text not null,
  enabled boolean not null default false,
  minimum_year smallint not null default 2022,
  latest_available_year smallint,
  country_coverage integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_organization, source_dataset, source_indicator_code)
);

create table if not exists public.stat_observations (
  category_id text not null references public.stat_categories(id) on delete cascade,
  country_iso3 text not null check (country_iso3 ~ '^[A-Z]{3}$'),
  country_name text not null,
  data_year smallint not null check (data_year between 1900 and 2100),
  value double precision not null,
  source_url text,
  source_record_id text,
  imported_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  primary key (category_id, country_iso3, data_year)
);

create index if not exists stat_observations_category_year_idx
  on public.stat_observations (category_id, data_year desc);

create index if not exists stat_observations_country_idx
  on public.stat_observations (country_iso3);

create table if not exists public.stat_import_runs (
  id bigint generated by default as identity primary key,
  source_organization text not null,
  source_dataset text not null,
  status text not null check (status in ('running', 'completed', 'failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  categories_processed integer not null default 0,
  observations_inserted integer not null default 0,
  observations_updated integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb
);

create or replace view public.stat_latest_values as
select distinct on (o.category_id, o.country_iso3)
  o.category_id,
  o.country_iso3,
  o.country_name,
  o.value,
  o.data_year,
  coalesce(o.source_url, c.source_url) as source_url,
  c.title,
  c.short_title,
  c.description,
  c.icon,
  c.unit,
  c.value_type,
  c.ranking_direction,
  c.family,
  c.source_organization,
  c.source_dataset,
  c.source_indicator_code
from public.stat_observations o
join public.stat_categories c on c.id = o.category_id
where c.enabled = true
  and o.data_year >= c.minimum_year
order by o.category_id, o.country_iso3, o.data_year desc, o.imported_at desc;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists stat_categories_set_updated_at on public.stat_categories;
create trigger stat_categories_set_updated_at
before update on public.stat_categories
for each row execute function public.set_updated_at();

alter table public.stat_categories enable row level security;
alter table public.stat_observations enable row level security;
alter table public.stat_import_runs enable row level security;

-- Public clients may read enabled category metadata and observations.
-- Inserts/updates remain blocked unless performed with the Supabase service-role key.
drop policy if exists "Public can read enabled categories" on public.stat_categories;
create policy "Public can read enabled categories"
on public.stat_categories
for select
using (enabled = true);

drop policy if exists "Public can read observations for enabled categories" on public.stat_observations;
create policy "Public can read observations for enabled categories"
on public.stat_observations
for select
using (
  exists (
    select 1
    from public.stat_categories c
    where c.id = stat_observations.category_id
      and c.enabled = true
  )
);

-- No public policy is created for stat_import_runs.
-- Only service-role/server-side processes should read or write import logs.

grant select on public.stat_categories to anon, authenticated;
grant select on public.stat_observations to anon, authenticated;
grant select on public.stat_latest_values to anon, authenticated;

commit;
