-- Canonical playable-country registry and automated category quality controls.
create table if not exists public.countries (
  iso3 text primary key,
  name text not null,
  playable boolean not null default true,
  region text,
  updated_at timestamptz not null default now()
);

alter table public.stat_categories add column if not exists quality_score integer not null default 0 check (quality_score between 0 and 100);
alter table public.stat_categories add column if not exists eligible_daily boolean not null default false;
alter table public.stat_categories add column if not exists quality_details jsonb not null default '{}'::jsonb;

insert into public.countries (iso3, name, playable) values
  ('AFG', 'Afghanistan', true),
  ('ALB', 'Albania', true),
  ('DZA', 'Algeria', true),
  ('AND', 'Andorra', true),
  ('AGO', 'Angola', true),
  ('ATG', 'Antigua and Barbuda', true),
  ('ARG', 'Argentina', true),
  ('ARM', 'Armenia', true),
  ('AUS', 'Australia', true),
  ('AUT', 'Austria', true),
  ('AZE', 'Azerbaijan', true),
  ('BHS', 'Bahamas', true),
  ('BHR', 'Bahrain', true),
  ('BGD', 'Bangladesh', true),
  ('BRB', 'Barbados', true),
  ('BLR', 'Belarus', true),
  ('BEL', 'Belgium', true),
  ('BLZ', 'Belize', true),
  ('BEN', 'Benin', true),
  ('BTN', 'Bhutan', true),
  ('BOL', 'Bolivia', true),
  ('BIH', 'Bosnia and Herzegovina', true),
  ('BWA', 'Botswana', true),
  ('BRA', 'Brazil', true),
  ('BRN', 'Brunei', true),
  ('BGR', 'Bulgaria', true),
  ('BFA', 'Burkina Faso', true),
  ('BDI', 'Burundi', true),
  ('CPV', 'Cabo Verde', true),
  ('KHM', 'Cambodia', true),
  ('CMR', 'Cameroon', true),
  ('CAN', 'Canada', true),
  ('CAF', 'Central African Republic', true),
  ('TCD', 'Chad', true),
  ('CHL', 'Chile', true),
  ('CHN', 'China', true),
  ('COL', 'Colombia', true),
  ('COM', 'Comoros', true),
  ('COG', 'Congo', true),
  ('COD', 'DR Congo', true),
  ('CRI', 'Costa Rica', true),
  ('CIV', 'Côte d’Ivoire', true),
  ('HRV', 'Croatia', true),
  ('CUB', 'Cuba', true),
  ('CYP', 'Cyprus', true),
  ('CZE', 'Czechia', true),
  ('DNK', 'Denmark', true),
  ('DJI', 'Djibouti', true),
  ('DMA', 'Dominica', true),
  ('DOM', 'Dominican Republic', true),
  ('ECU', 'Ecuador', true),
  ('EGY', 'Egypt', true),
  ('SLV', 'El Salvador', true),
  ('GNQ', 'Equatorial Guinea', true),
  ('ERI', 'Eritrea', true),
  ('EST', 'Estonia', true),
  ('SWZ', 'Eswatini', true),
  ('ETH', 'Ethiopia', true),
  ('FJI', 'Fiji', true),
  ('FIN', 'Finland', true),
  ('FRA', 'France', true),
  ('GAB', 'Gabon', true),
  ('GMB', 'Gambia', true),
  ('GEO', 'Georgia', true),
  ('DEU', 'Germany', true),
  ('GHA', 'Ghana', true),
  ('GRC', 'Greece', true),
  ('GRD', 'Grenada', true),
  ('GTM', 'Guatemala', true),
  ('GIN', 'Guinea', true),
  ('GNB', 'Guinea-Bissau', true),
  ('GUY', 'Guyana', true),
  ('HTI', 'Haiti', true),
  ('HND', 'Honduras', true),
  ('HUN', 'Hungary', true),
  ('ISL', 'Iceland', true),
  ('IND', 'India', true),
  ('IDN', 'Indonesia', true),
  ('IRN', 'Iran', true),
  ('IRQ', 'Iraq', true),
  ('IRL', 'Ireland', true),
  ('ISR', 'Israel', true),
  ('ITA', 'Italy', true),
  ('JAM', 'Jamaica', true),
  ('JPN', 'Japan', true),
  ('JOR', 'Jordan', true),
  ('KAZ', 'Kazakhstan', true),
  ('KEN', 'Kenya', true),
  ('KIR', 'Kiribati', true),
  ('PRK', 'North Korea', true),
  ('KOR', 'South Korea', true),
  ('KWT', 'Kuwait', true),
  ('KGZ', 'Kyrgyzstan', true),
  ('LAO', 'Laos', true),
  ('LVA', 'Latvia', true),
  ('LBN', 'Lebanon', true),
  ('LSO', 'Lesotho', true),
  ('LBR', 'Liberia', true),
  ('LBY', 'Libya', true),
  ('LIE', 'Liechtenstein', true),
  ('LTU', 'Lithuania', true),
  ('LUX', 'Luxembourg', true),
  ('MDG', 'Madagascar', true),
  ('MWI', 'Malawi', true),
  ('MYS', 'Malaysia', true),
  ('MDV', 'Maldives', true),
  ('MLI', 'Mali', true),
  ('MLT', 'Malta', true),
  ('MHL', 'Marshall Islands', true),
  ('MRT', 'Mauritania', true),
  ('MUS', 'Mauritius', true),
  ('MEX', 'Mexico', true),
  ('FSM', 'Micronesia, Federated States of', true),
  ('MDA', 'Moldova', true),
  ('MCO', 'Monaco', true),
  ('MNG', 'Mongolia', true),
  ('MNE', 'Montenegro', true),
  ('MAR', 'Morocco', true),
  ('MOZ', 'Mozambique', true),
  ('MMR', 'Myanmar', true),
  ('NAM', 'Namibia', true),
  ('NRU', 'Nauru', true),
  ('NPL', 'Nepal', true),
  ('NLD', 'Netherlands', true),
  ('NZL', 'New Zealand', true),
  ('NIC', 'Nicaragua', true),
  ('NER', 'Niger', true),
  ('NGA', 'Nigeria', true),
  ('MKD', 'North Macedonia', true),
  ('NOR', 'Norway', true),
  ('OMN', 'Oman', true),
  ('PAK', 'Pakistan', true),
  ('PLW', 'Palau', true),
  ('PAN', 'Panama', true),
  ('PNG', 'Papua New Guinea', true),
  ('PRY', 'Paraguay', true),
  ('PER', 'Peru', true),
  ('PHL', 'Philippines', true),
  ('POL', 'Poland', true),
  ('PRT', 'Portugal', true),
  ('QAT', 'Qatar', true),
  ('ROU', 'Romania', true),
  ('RUS', 'Russia', true),
  ('RWA', 'Rwanda', true),
  ('KNA', 'Saint Kitts and Nevis', true),
  ('LCA', 'Saint Lucia', true),
  ('VCT', 'Saint Vincent and the Grenadines', true),
  ('WSM', 'Samoa', true),
  ('SMR', 'San Marino', true),
  ('STP', 'Sao Tome and Principe', true),
  ('SAU', 'Saudi Arabia', true),
  ('SEN', 'Senegal', true),
  ('SRB', 'Serbia', true),
  ('SYC', 'Seychelles', true),
  ('SLE', 'Sierra Leone', true),
  ('SGP', 'Singapore', true),
  ('SVK', 'Slovakia', true),
  ('SVN', 'Slovenia', true),
  ('SLB', 'Solomon Islands', true),
  ('SOM', 'Somalia', true),
  ('ZAF', 'South Africa', true),
  ('SSD', 'South Sudan', true),
  ('ESP', 'Spain', true),
  ('LKA', 'Sri Lanka', true),
  ('SDN', 'Sudan', true),
  ('SUR', 'Suriname', true),
  ('SWE', 'Sweden', true),
  ('CHE', 'Switzerland', true),
  ('SYR', 'Syria', true),
  ('TJK', 'Tajikistan', true),
  ('TZA', 'Tanzania', true),
  ('THA', 'Thailand', true),
  ('TLS', 'Timor-Leste', true),
  ('TGO', 'Togo', true),
  ('TON', 'Tonga', true),
  ('TTO', 'Trinidad and Tobago', true),
  ('TUN', 'Tunisia', true),
  ('TUR', 'Türkiye', true),
  ('TKM', 'Turkmenistan', true),
  ('TUV', 'Tuvalu', true),
  ('UGA', 'Uganda', true),
  ('UKR', 'Ukraine', true),
  ('ARE', 'United Arab Emirates', true),
  ('GBR', 'United Kingdom', true),
  ('USA', 'United States', true),
  ('URY', 'Uruguay', true),
  ('UZB', 'Uzbekistan', true),
  ('VUT', 'Vanuatu', true),
  ('VEN', 'Venezuela', true),
  ('VNM', 'Vietnam', true),
  ('YEM', 'Yemen', true),
  ('ZMB', 'Zambia', true),
  ('ZWE', 'Zimbabwe', true),
  ('PSE', 'State of Palestine', true),
  ('VAT', 'Holy See', true)
on conflict (iso3) do update set name=excluded.name, playable=true, updated_at=now();

update public.countries set playable=false where iso3 not in ('AFG','ALB','DZA','AND','AGO','ATG','ARG','ARM','AUS','AUT','AZE','BHS','BHR','BGD','BRB','BLR','BEL','BLZ','BEN','BTN','BOL','BIH','BWA','BRA','BRN','BGR','BFA','BDI','CPV','KHM','CMR','CAN','CAF','TCD','CHL','CHN','COL','COM','COG','COD','CRI','CIV','HRV','CUB','CYP','CZE','DNK','DJI','DMA','DOM','ECU','EGY','SLV','GNQ','ERI','EST','SWZ','ETH','FJI','FIN','FRA','GAB','GMB','GEO','DEU','GHA','GRC','GRD','GTM','GIN','GNB','GUY','HTI','HND','HUN','ISL','IND','IDN','IRN','IRQ','IRL','ISR','ITA','JAM','JPN','JOR','KAZ','KEN','KIR','PRK','KOR','KWT','KGZ','LAO','LVA','LBN','LSO','LBR','LBY','LIE','LTU','LUX','MDG','MWI','MYS','MDV','MLI','MLT','MHL','MRT','MUS','MEX','FSM','MDA','MCO','MNG','MNE','MAR','MOZ','MMR','NAM','NRU','NPL','NLD','NZL','NIC','NER','NGA','MKD','NOR','OMN','PAK','PLW','PAN','PNG','PRY','PER','PHL','POL','PRT','QAT','ROU','RUS','RWA','KNA','LCA','VCT','WSM','SMR','STP','SAU','SEN','SRB','SYC','SLE','SGP','SVK','SVN','SLB','SOM','ZAF','SSD','ESP','LKA','SDN','SUR','SWE','CHE','SYR','TJK','TZA','THA','TLS','TGO','TON','TTO','TUN','TUR','TKM','TUV','UGA','UKR','ARE','GBR','USA','URY','UZB','VUT','VEN','VNM','YEM','ZMB','ZWE','PSE','VAT');
create index if not exists countries_playable_idx on public.countries(playable);
create index if not exists stat_categories_daily_quality_idx on public.stat_categories(eligible_daily, quality_score desc);
