-- GeoStats v12.1.0: strict candidate intake and editorial review workflow
-- New sources enter quarantine and cannot become playable until they pass
-- automated quality gates and an administrator explicitly approves them.

begin;

alter table public.stat_categories
  add column if not exists review_status text not null default 'candidate',
  add column if not exists evidence_tier text,
  add column if not exists auto_qualified boolean not null default false,
  add column if not exists common_year smallint,
  add column if not exists common_year_coverage integer not null default 0,
  add column if not exists official_observation_share double precision,
  add column if not exists modeled_observation_share double precision,
  add column if not exists clustering_score smallint,
  add column if not exists stability_score smallint,
  add column if not exists methodology_notes text,
  add column if not exists quality_standard_version text not null default 'strict-v1';

-- Add constraints separately so this migration remains idempotent.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'stat_categories_review_status_check'
      and conrelid = 'public.stat_categories'::regclass
  ) then
    alter table public.stat_categories
      add constraint stat_categories_review_status_check
      check (review_status in ('candidate','needs_review','approved','rejected'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'stat_categories_evidence_tier_check'
      and conrelid = 'public.stat_categories'::regclass
  ) then
    alter table public.stat_categories
      add constraint stat_categories_evidence_tier_check
      check (evidence_tier is null or evidence_tier in ('A','B','C'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'stat_categories_share_range_check'
      and conrelid = 'public.stat_categories'::regclass
  ) then
    alter table public.stat_categories
      add constraint stat_categories_share_range_check
      check (
        (official_observation_share is null or official_observation_share between 0 and 1)
        and (modeled_observation_share is null or modeled_observation_share between 0 and 1)
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'stat_categories_quality_subscore_check'
      and conrelid = 'public.stat_categories'::regclass
  ) then
    alter table public.stat_categories
      add constraint stat_categories_quality_subscore_check
      check (
        (clustering_score is null or clustering_score between 0 and 100)
        and (stability_score is null or stability_score between 0 and 100)
      );
  end if;
end $$;

create index if not exists stat_categories_review_status_idx
  on public.stat_categories (review_status, source_organization);

create index if not exists stat_categories_auto_qualified_idx
  on public.stat_categories (auto_qualified, review_status)
  where auto_qualified = true;

create or replace function public.clear_stat_source_observations(
  p_source_organization text,
  p_source_dataset text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  removed bigint;
begin
  delete from public.stat_observations
  where category_id in (
    select id from public.stat_categories
    where source_organization = p_source_organization
      and source_dataset = p_source_dataset
  );
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.clear_stat_source_observations(text,text) from public, anon, authenticated;
grant execute on function public.clear_stat_source_observations(text,text) to service_role;

create table if not exists public.stat_category_reviews (
  id bigint generated by default as identity primary key,
  category_id text not null references public.stat_categories(id) on delete cascade,
  reviewer_user_id uuid not null,
  decision text not null check (decision in ('approved','rejected','reset')),
  notes text,
  quality_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists stat_category_reviews_category_idx
  on public.stat_category_reviews (category_id, created_at desc);

alter table public.stat_category_reviews enable row level security;

-- Existing World Bank rows keep their current playable state. Future external
-- imports default to quarantine until explicitly reviewed.
update public.stat_categories
set
  review_status = case when eligible_daily then 'approved' else 'candidate' end,
  auto_qualified = eligible_daily,
  evidence_tier = case when eligible_daily then 'B' else evidence_tier end,
  common_year = coalesce(common_year, latest_available_year),
  common_year_coverage = greatest(common_year_coverage, country_coverage),
  quality_standard_version = 'legacy-world-bank-v1'
where source_organization = 'World Bank'
  and review_status = 'candidate';

insert into public.data_sources(id,name,description,status,display_order,metadata)
values (
  'faostat',
  'FAOSTAT',
  'FAO crop and livestock production candidates imported into strict review quarantine.',
  'active',
  20,
  jsonb_build_object(
    'dataset', 'Production: Crops and livestock products (QCL)',
    'workflow', 'import-faostat.yml',
    'intake_policy', 'strict-v1',
    'review_required', true
  )
)
on conflict(id) do update set
  name = excluded.name,
  description = excluded.description,
  status = excluded.status,
  display_order = excluded.display_order,
  metadata = coalesce(public.data_sources.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

insert into public.data_sources(id,name,description,status,display_order,metadata)
values
  ('comtrade','UN Comtrade','Curated merchandise trade values and quantities, subject to mirror-data and comparability checks.','planned',60,'{"intake_policy":"strict-v1","review_required":true}'::jsonb),
  ('unsd-energy','UNSD Energy','Energy production, transformation, trade, and consumption candidates.','planned',70,'{"intake_policy":"strict-v1","review_required":true}'::jsonb),
  ('ilostat','ILOSTAT','Internationally harmonized labor indicators screened for survey comparability and clustering.','planned',80,'{"intake_policy":"strict-v1","review_required":true}'::jsonb),
  ('climate','Global climate and geography','Consistently measured physical climate and geography candidates.','planned',90,'{"intake_policy":"strict-v1","review_required":true}'::jsonb),
  ('wipo','WIPO','Intellectual-property activity candidates with coverage and reporting-quality controls.','planned',100,'{"intake_policy":"strict-v1","review_required":true}'::jsonb)
on conflict(id) do update set
  name = excluded.name,
  description = excluded.description,
  display_order = excluded.display_order,
  metadata = coalesce(public.data_sources.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

commit;
